### ISSUE TITLE
Windows Install Errors

### ISSUE THREAD

**Issue by alvinquantum** [jpmorganchase/QOKit#13]
I'm using Windows 10. When installing qokit using a conda environment with Python 3.11, pytest fails with 12 errors. When installing qokit using a conda environment with Python 3.9, pytest passes 99 tests and fails 1 test:

`tests/test_labs.py::test_gate_optimized_terms_greedy - ValueError: high is out of bounds for int32`

Note: I am running 64 bit python in both scenarios.

**Comment by rsln-s** [comment]
Resolved by #15. Thank you for reporting, @alvinquantum! See also #14
