### ISSUE TITLE
Flip order of beta and gamma in MaxCut circuit

### ISSUE THREAD

**Issue by ZichangHe** [jpmorganchase/QOKit#38]
Flip the order of gamma and beta in MaxCut circuit generation: https://github.com/jpmorganchase/QOKit/blob/492b7d43002664c447ad873435c393a864d91186/qokit/qaoa_circuit_maxcut.py#L34

**Comment by rsln-s** [comment]
This change is also needed in `qaoa_circuit_labs.py`

**Comment by rsln-s** [comment]
Resolved by #48
