### ISSUE TITLE
Badge is not rendering

### ISSUE THREAD

**Issue by rsln-s** [jpmorganchase/QOKit#6]
"tests passing" badge does not render in public version as it points to the wrong repo

**Comment by alex124585** [comment]
sure

**Comment by alex124585** [comment]
> @alex124585 would you mind fixing this?

fixed

**Comment by rsln-s** [comment]
Fixed by [5892cad](https://github.com/jpmorganchase/QOKit/commit/5892cad45cae25fc72d310c0f8ffd2c9bc34f4d7)
