### ISSUE TITLE
error when installing qokit from pypl

### ISSUE THREAD

**Issue by ZichangHe** [jpmorganchase/QOKit#61]
in python3.9, pip install qokit

when import qokit, it has errors:
ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168

The error will disappear when install qokit through: 
git clone and pip install -e .

**Comment by rsln-s** [comment]
@ZichangHe I think this may be a JPMC-internal error since it does not appear in the pipeline on Github. Downgrading urllib3 (`pip install -U urllib3==1.26.6`) resolved this issue for me in the past.

**Comment by ZichangHe** [comment]
Thanks for clarifying!
